source activate openmm-7.1
module load cuda/8.0.44
python3 blues.py > blues.log
source deactivate openmm-7.1

# post-processing blues MD trajectory for torsion distribution
module load amber/18
cpptraj -i ../dihedral.ptraj

# find accepted moves
python3 ../../../scripts/findAcceptedMove.py gmx.log

# calculate number of moves accepted as a function of total number of iterations proposed
python3 ../../../scripts/findAcceptanceIteration.py gmx.log acc_ncmc_XYZNCMC.txt
